artifact_location: /Users/ashishsingh/github/MLflow-tutorials/custom_path/372275770995623464
creation_time: 1704839159344
experiment_id: '372275770995623464'
last_update_time: 1704839159344
lifecycle_stage: active
name: experment_set_get_tracking_uri
